[package]
name = "graph-renderer"
version = "0.1.3"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
proc_macros = { path = "../proc_macros" }

[features]
trace = []
