name: Publish Node.js Package to GitHub Packages

on:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  packages: write
  id-token: write

jobs:
  setup-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91.1
          target: wasm32-unknown-unknown
          components: clippy, rustfmt
          rust-src-dir: src/graph-renderer
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

  format-and-lint:
    runs-on: ubuntu-latest
    needs: setup-rust

    defaults:
      run:
        working-directory: ./src/graph-renderer

    steps:
      - name: Clippy Check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features --workspace -- -A dead_code -D warnings # cargo clippy --all-targets --all-features --workspace -- -A dead_code -D warnings
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build:
    runs-on: ubuntu-latest
    needs: setup-rust
    steps:
      - name: Compile rust to wasm
        run: npm run compileWasm
      - run: mkdir -p dist/graph-renderer
      - run: cp -r src/graph-renderer/pkg dist/graph-renderer

      - uses: actions/setup-node@v6
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: mv package.json dist/package.json
      - uses: actions/upload-artifact@v5
        with:
          name: package-artifact
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    permissions:
      contents: read
      packages: write # Grant write access to packages
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: package-artifact
          path: . # Download artifact to current directory
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/download-artifact@v6
        with:
          name: package-artifact
          path: dist
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: "npm ci"
      - name: Build
        run: "npm run buildExamples"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: "github-pages"
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
