name: Main

on: push

permissions:
  contents: write
  pages: write
  packages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91.1
          target: wasm32-unknown-unknown
          components: clippy, rustfmt
          rust-src-dir: src/graph-renderer
      - name: Lint Wasm
        run: npm run lintWasm

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91.1
          target: wasm32-unknown-unknown
          rust-src-dir: src/graph-renderer
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Compile rust to wasm
        run: npm run compileWasm

      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          scope: "@izumiano"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build
      - run: npm test
      - run: mv package.json dist/package.json
      - uses: actions/upload-artifact@v5
        with:
          name: package-artifact
          path: dist
  
  publish-package:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [lint, build]
    name: Publish to GitHub Packages
    uses: ./.github/workflows/publish-package.yml
    with:
      artifact-name: package-artifact
      run-id: ${{ github.run_id }}
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
  
  deploy-pages:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    needs: [lint, build]
    name: Deploy examples page
    uses: ./.github/workflows/deploy-pages.yml
    with:
      artifact-name: package-artifact
      run-id: ${{ github.run_id }}
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pages: write
      packages: write
      id-token: write

