name: Publish Node.js Package to GitHub Packages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91.1
          target: wasm32-unknown-unknown
          rust-src-dir: src/graph-renderer
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Compile rust to wasm
        run: npm run compileWasm
      - run: mkdir -p dist/graph-renderer
      - run: cp -r src/graph-renderer/pkg dist/graph-renderer

      - uses: actions/setup-node@v6
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: mv package.json dist/package.json
      - uses: actions/upload-artifact@v5
        with:
          name: package-artifact
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    permissions:
      contents: read
      packages: write # Grant write access to packages
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: package-artifact
          path: . # Download artifact to current directory
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
